### ISSUE TITLE
Sending an API request with a URI above the limit breaks the library's exception handling

### ISSUE THREAD

**Issue by Ckoshnick** [osimloeff/PI-Web-API-Client-Python#6]
I attempted to pull ~300 tags in a single get_summaries_ad_hoc() call.  I first encountered the following traceback

Traceback (most recent call last):

  File "<ipython-input-136-0c4861ee5d29>", line 8, in <module>
    calculation='recorded', interval=interval)

  File "C:\Users\koshnick\Documents\Git Zone\PI_client\v3_0.py", line 1043, in get_stream_by_point
    time_zone=self.time_zone).items

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api\stream_set_api.py", line 1692, in get_recorded_ad_hoc
    (data) = self.get_recorded_ad_hoc_with_http_info(web_id, boundary_type, end_time, filter_expression, include_filtered_values, max_count, selected_fields, sort_field, sort_order, start_time, time_zone, web_id_type, **kwargs)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api\stream_set_api.py", line 1784, in get_recorded_ad_hoc_with_http_info
    collection_formats =collection_formats)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py", line 311, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py", line 139, in __call_api
    body=body)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py", line 329, in request
    headers=headers)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\rest.py", line 77, in send_request
    raise ApiException(http_resp=response)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\rest.py", line 88, in __init__
    self.error = json.loads(self.body)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\koshnick\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

After commenting out line 88 in the rest.py module
88 #            self.error = json.loads(self.body)

so that the actual API error traceback made it through. That is pasted below.

ApiException: (414)
Reason: Request-URI Too Long
HTTP response headers: {'Content-Type': 'text/html; charset=us-ascii', 'Server': 'Microsoft-HTTPAPI/2.0', 'Date': 'Thu, 11 Oct 2018 21:50:42 GMT', 'Connection': 'close', 'Content-Length': '329'}
HTTP response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Request URL Too Long</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Request URL Too Long</h2>
<hr><p>HTTP Error 414. The request URL is too long.</p>
</BODY></HTML>

The ApiException class should be improved to handle this exception properly. 

I am attempting a work around where any request made by my code will chunk the number of points into 50 point groups and concatenate all of the data in the end. A functionality where the library does it own chunking for requests that exceed the URL length limit would be great!

**Comment by osimloeff** [comment]
Thanks for letting me know about this issue! Yes, it makes sense. I wonder how many people have faced this issue as well.
